// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SIGEAC.Data;

#nullable disable

namespace SIGEAC.Migrations
{
    [DbContext(typeof(SigeacDbContext))]
    [Migration("20250914161914_CrearTablasComponentesPerifericosEquipos")]
    partial class CrearTablasComponentesPerifericosEquipos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EquipoUsuario", b =>
                {
                    b.Property<int>("EquipoID_Equipo")
                        .HasColumnType("int");

                    b.Property<int>("UsuariosAutorizadosID_Usuario")
                        .HasColumnType("int");

                    b.HasKey("EquipoID_Equipo", "UsuariosAutorizadosID_Usuario");

                    b.HasIndex("UsuariosAutorizadosID_Usuario");

                    b.ToTable("EquipoUsuario");
                });

            modelBuilder.Entity("SIGEAC.Models.Componente", b =>
                {
                    b.Property<int>("ID_Componente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Componente"));

                    b.Property<int?>("EquipoID")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Componente");

                    b.HasIndex("EquipoID");

                    b.ToTable("Componentes");
                });

            modelBuilder.Entity("SIGEAC.Models.Equipo", b =>
                {
                    b.Property<int>("ID_Equipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Equipo"));

                    b.Property<string>("Adicionales")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Antivirus")
                        .HasColumnType("bit");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Cifrado")
                        .HasColumnType("bit");

                    b.Property<string>("Confidencialidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContrasenaCifrado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Criticidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Disponibilidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DisponibilidadFisica")
                        .HasColumnType("bit");

                    b.Property<int>("EmpleadoAsignadoID")
                        .HasColumnType("int");

                    b.Property<bool>("EscritorioRemoto")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaClasificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentificadorActivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Integridad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MAC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroSerie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PropiedadActivo")
                        .HasColumnType("bit");

                    b.Property<int>("PuestoID")
                        .HasColumnType("int");

                    b.Property<string>("SistemaOperativo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Soporte")
                        .HasColumnType("bit");

                    b.Property<bool>("Tipo")
                        .HasColumnType("bit");

                    b.Property<bool>("VPNLabs")
                        .HasColumnType("bit");

                    b.Property<string>("VersionSO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Equipo");

                    b.HasIndex("EmpleadoAsignadoID")
                        .IsUnique();

                    b.HasIndex("IdentificadorActivo")
                        .IsUnique();

                    b.HasIndex("PuestoID")
                        .IsUnique();

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("SIGEAC.Models.Periferico", b =>
                {
                    b.Property<int>("ID_Periferico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Periferico"));

                    b.Property<int?>("EquipoID")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Periferico");

                    b.HasIndex("EquipoID");

                    b.ToTable("Perifericos");
                });

            modelBuilder.Entity("SIGEAC.Models.Puesto", b =>
                {
                    b.Property<int>("ID_Puesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Puesto"));

                    b.Property<int?>("EquipoID")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("ID_Puesto");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Puestos");
                });

            modelBuilder.Entity("SIGEAC.Models.Usuario", b =>
                {
                    b.Property<int>("ID_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Usuario"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Usuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            ID_Usuario = 1,
                            Apellido = "Principal",
                            Contrasena = "Admin123",
                            DNI = "00000001",
                            Email = "admin@sigeac.com",
                            Nombre = "Admin",
                            Rol = "Administrador"
                        },
                        new
                        {
                            ID_Usuario = 2,
                            Apellido = "Principal",
                            Contrasena = "RRHH123",
                            DNI = "00000002",
                            Email = "rrhh@sigeac.com",
                            Nombre = "RRHH",
                            Rol = "RRHH"
                        });
                });

            modelBuilder.Entity("EquipoUsuario", b =>
                {
                    b.HasOne("SIGEAC.Models.Equipo", null)
                        .WithMany()
                        .HasForeignKey("EquipoID_Equipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIGEAC.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuariosAutorizadosID_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SIGEAC.Models.Componente", b =>
                {
                    b.HasOne("SIGEAC.Models.Equipo", "Equipo")
                        .WithMany("Componentes")
                        .HasForeignKey("EquipoID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("SIGEAC.Models.Equipo", b =>
                {
                    b.HasOne("SIGEAC.Models.Usuario", "EmpleadoAsignado")
                        .WithOne()
                        .HasForeignKey("SIGEAC.Models.Equipo", "EmpleadoAsignadoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIGEAC.Models.Puesto", "Puesto")
                        .WithOne("Equipo")
                        .HasForeignKey("SIGEAC.Models.Equipo", "PuestoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmpleadoAsignado");

                    b.Navigation("Puesto");
                });

            modelBuilder.Entity("SIGEAC.Models.Periferico", b =>
                {
                    b.HasOne("SIGEAC.Models.Equipo", "Equipo")
                        .WithMany("Perifericos")
                        .HasForeignKey("EquipoID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("SIGEAC.Models.Puesto", b =>
                {
                    b.HasOne("SIGEAC.Models.Usuario", "Empleado")
                        .WithMany()
                        .HasForeignKey("UsuarioID");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("SIGEAC.Models.Equipo", b =>
                {
                    b.Navigation("Componentes");

                    b.Navigation("Perifericos");
                });

            modelBuilder.Entity("SIGEAC.Models.Puesto", b =>
                {
                    b.Navigation("Equipo");
                });
#pragma warning restore 612, 618
        }
    }
}
